[package]
name = "cimdea"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duckdb="*"
datafusion="*"
polars="0.30"
sql-builder="3.1"
lazy_static="*"
extended = "*"
ascii = "*"
